# input
input_sources: "input_sources.csv" # Specify the CSV file containing the input sources
ignore_non_valid_files: False # Ignore file from workflow if no valid sequence present in the file, instead of error message

# flow of operations
use_orthofisher: False  # Set to True to use OrthoFisher analysis path. When False, the will OrthoFinder+OrthoSNAP path will be used.
supermatrix: True  # Infer a tree using the supermatrix method
supertree: True  # Infer a tree using the supertree (ASTRAL) method

summarize_information_content: True

# gene and alignment filtering
orthofinder_use_scogs: True  # Use the single-copy orthogroups (when using de novo ortholog analysis path)
orthofinder_use_snap_ogs: True  # Use the SNAP orthogroups (when using de novo ortholog analysis path)
ortholog_min_seqs: 5  # Needs to be 3 or larger. Minimum number of sequences that needs to be in an alignment for it to proceed to phylogenetic analysis.
ortholog_min_taxa: 5  # Minimum number of taxa that needs to be in an orthogroup.
# orthosnap_occupancy: 5 # Uncomment this line if you wish to set the orthosnap_occupancy to be something other than ortholog_min_seqs
minimum_trimmed_alignment_length_cds: 501  # Any CDS alignments shorter than this will not be used for phylogeny inference
minimum_trimmed_alignment_length_proteins: 167  # Any protein alignments shorter than this will not be used for phylogeny inference
max_trimmed_proportion: 0.5  # Any alignments for which more than this fraction of sites was removed during alignment trimming will not be used for phylogeny inference

# tree inference settings
infer_tree_with_protein_seqs: True  # If True, trees will be inferred from protein alignments
infer_tree_with_cds_seqs: True  # If True, trees will be inferred from nucleotide alignments
bootstrap_string: "-bb 1000"  # Use IQ-tree syntax, e.g. "-b 100" for 100 nonparametric bootstraps or "-bb 1000" for 1000 ultrafast bootstraps
model_string: "-m TEST"  # Use IQ-tree syntax, e.g. "-m TEST" to activate ModelFinder or "-m GTR+F+G" for a nucleotide GTR model with empirical base frequencies and discrete gamma model for rate heterogeneity
#supermatrix_outgroup: "Derbesia_sp_WEST4838"  # Uncomment this line if you wish to specify an outgroup for tree inference

# list of hmmer files for orthofisher
# TODO: glob for HMMs
orthofisher_hmmer_files:
  - hmms/1080at3041.hmm
  - hmms/1103at3041.hmm
  - hmms/1271at3041.hmm
  - hmms/1379at3041.hmm
  - hmms/1518at3041.hmm
  - hmms/1569at3041.hmm
  - hmms/1610at3041.hmm
  - hmms/171at3041.hmm
  - hmms/1738at3041.hmm
  - hmms/3239at3041.hmm
  - hmms/336at3041.hmm
  - hmms/3380at3041.hmm
  - hmms/345at3041.hmm
  - hmms/3499at3041.hmm
  - hmms/3624at3041.hmm
  - hmms/4242at3041.hmm
  - hmms/4605at3041.hmm
  - hmms/4751at3041.hmm
  - hmms/4759at3041.hmm
  - hmms/5839at3041.hmm
  - hmms/6145at3041.hmm
  - hmms/6593at3041.hmm
  - hmms/6989at3041.hmm
  - hmms/911at3041.hmm
  - hmms/9903at3041.hmm
  - hmms/992at3041.hmm